name: Comunicador de la Legiòn del Mal


on:
  workflow_dispatch:
    inputs:
      villano:
        description: "Que villano envìa el mensaje?"
        required: true
        type: choice
        options: 
          - Lex Luthor
          - Magneto
          - Jocker
          - Mystique
          - Green Goblin

jobs:

  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 
        run: 

      - name: 
        run: |
      
