name: Comunicador de la Legiòn del Mal


on:
  workflow_dispatch:
    inputs:
      villano:
        description: "Que villano envìa el mensaje?"
        required: true
        type: choice
        options: 
          - Lex Luthor
          - Magneto
          - Jocker
          - Mystique
          - Green Goblin
      mensaje:
        description: "Mensaje para el consejo"
        required: true
        default: "La mision fue un èxito"       

        # cow_character:

      cow_character:
        description: "Character"
        required: true
        type: choice
        options: 
          - eyes
          - ghostbusters
          - dragon
          - homer
          - R2-D2


        
      prioridad:
        description: "Nivel de prioridad"
        required: true
        type: choice
        options: 
          - 🟢 Normal
          - 🟡 Alta
          - 🔴 Crìtica
          

jobs:

  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar el transmisor de la Legiòn del Mal
        run: sudo apt-get install -y cowsay

      - name: Imprimir inputs
        run: |
          echo "==========================="
          echo "    Transmisiòn interceptada     "
          echo "==========================="
          echo " "
          echo "De: ${{ inputs.villano }}"
          echo ""
          echo "Fecha: $(date -u +"%d/%m/%Y - %H:%M UTC")"
          echo "------- Mensaje --------"
          echo "Nivel: ${{ inputs.prioridad }}"
          cowsay -f "${{ inputs.cow_character }}" "${{ inputs.mensaje }}"
          echo ""
          echo "------${{ inputs.villano }}"
          echo "..."
                
